# Generated by Django 4.2 on 2023-07-04 17:41

from django.db import migrations
import filebrowser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=filebrowser.fields.FileBrowseField(verbose_name='بارگذاری تصویر'),
        ),
    ]
