# Generated by Django 4.2 on 2023-07-04 18:08

from django.db import migrations
import filebrowser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=filebrowser.fields.FileBrowseField(max_length=200, verbose_name='Image'),
        ),
    ]
