# Generated by Django 4.2 on 2023-07-31 19:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0010_alter_product_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='user_like',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL, verbose_name='لایک'),
        ),
    ]
