# Generated by Django 4.2 on 2023-07-11 18:22

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='درباره ما', max_length=300, verbose_name='درباره ما')),
                ('context', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='متن')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال / غیرفعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'درباره ما',
                'verbose_name_plural': 'درباره ما',
            },
        ),
    ]
