# Generated by Django 4.2 on 2023-07-30 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_alter_blog_options_alter_blog_user_commentblog'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCommentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_heart', models.IntegerField(verbose_name='تعداد قلبها')),
                ('like', models.IntegerField(verbose_name='تعداد لایک ها')),
                ('dislike', models.IntegerField(verbose_name='تعداد دیسلایکها')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blog_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like', to='blog.commentblog', verbose_name='کامنت')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_comment_like', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
    ]
