# Generated by Django 4.2 on 2023-07-30 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogcommentlike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcommentlike',
            name='count_heart',
        ),
        migrations.RemoveField(
            model_name='blogcommentlike',
            name='dislike',
        ),
        migrations.RemoveField(
            model_name='blogcommentlike',
            name='like',
        ),
        migrations.AddField(
            model_name='blogcommentlike',
            name='dislike_count',
            field=models.IntegerField(default=0, verbose_name='تعداد دیسلایکها'),
        ),
        migrations.AddField(
            model_name='blogcommentlike',
            name='heart_count',
            field=models.IntegerField(default=0, verbose_name='تعداد قلبها'),
        ),
        migrations.AddField(
            model_name='blogcommentlike',
            name='like_count',
            field=models.IntegerField(default=0, verbose_name='تعداد لایک ها'),
        ),
    ]
