# Generated by Django 4.2 on 2023-07-30 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0004_remove_blogcommentlike_count_heart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcommentlike',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_comment_like', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
