# Generated by Django 4.2 on 2023-07-31 16:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0005_alter_blogcommentlike_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentblog',
            name='dislike_count',
            field=models.IntegerField(default=0, verbose_name='تعداد دیسلایکها'),
        ),
        migrations.AddField(
            model_name='commentblog',
            name='like_count',
            field=models.IntegerField(default=0, verbose_name='تعداد لایک ها'),
        ),
        migrations.AddField(
            model_name='commentblog',
            name='user_reaction',
            field=models.ManyToManyField(blank=True, null=True, related_name='blog_comment_like', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.DeleteModel(
            name='BlogCommentLike',
        ),
    ]
