# Generated by Django 4.2 on 2023-07-31 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_commentblog_user_reaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentblog',
            name='dislike_count',
        ),
    ]
