# Generated by Django 4.2 on 2023-08-05 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_commentblog_dislike_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='عنوان')),
                ('image', models.ImageField(upload_to='blog/header/%y/%m/', verbose_name='تصویر')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال / غیرفعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blog', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blog_header', to='blog.blog', verbose_name='وبلاگ مرتبط')),
            ],
            options={
                'verbose_name': 'بلاگ بنر',
                'verbose_name_plural': 'بلاگ بنر',
            },
        ),
    ]
