# Generated by Django 4.2 on 2023-07-27 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertiseBottomIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='advertise/bottom', verbose_name='تصویر')),
                ('alt', models.CharField(blank=True, max_length=400, null=True, verbose_name='توضیحات تصویر')),
                ('link', models.TextField(verbose_name='آدرس ریدایرکت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال / غیرفعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'تبلیغ صفحه اصلی - قسمت وسطی',
                'verbose_name_plural': 'تبلیغ صفحه اصلی - قسمت وسطی',
            },
        ),
        migrations.CreateModel(
            name='AdvertiseMiddleIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='advertise/middle', verbose_name='تصویر')),
                ('alt', models.CharField(blank=True, max_length=400, null=True, verbose_name='توضیحات تصویر')),
                ('link', models.TextField(verbose_name='آدرس ریدایرکت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال / غیرفعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'تبلیغ صفحه اصلی - قسمت وسطی',
                'verbose_name_plural': 'تبلیغ صفحه اصلی - قسمت وسطی',
            },
        ),
        migrations.CreateModel(
            name='AdvertiseTopIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='advertise/top', verbose_name='تصویر')),
                ('alt', models.CharField(blank=True, max_length=400, null=True, verbose_name='توضیحات تصویر')),
                ('link', models.TextField(verbose_name='آدرس ریدایرکت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال / غیرفعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'تبلیغ صفحه اصلی - قسمت بالایی',
                'verbose_name_plural': 'تبلیغ صفحه اصلی - قسمت بالایی',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slider', verbose_name='تصویر')),
                ('alt', models.CharField(blank=True, max_length=400, null=True, verbose_name='توضیحات تصویر')),
                ('link', models.TextField(verbose_name='آدرس ریدایرکت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال / غیرفعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'اسلایدر',
                'verbose_name_plural': 'اسلایدر',
            },
        ),
    ]
