# Generated by Django 4.2 on 2023-07-28 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterCapability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=600, verbose_name='عنوان')),
                ('image', models.ImageField(upload_to='footer/capability')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال / غیرفعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'توانمندی ها - فوتر',
                'verbose_name_plural': 'توانمندی ها - فوتر',
            },
        ),
        migrations.AlterModelOptions(
            name='advertisebottomindex',
            options={'verbose_name': 'تبلیغ صفحه اصلی - قسمت پایینی', 'verbose_name_plural': 'تبلیغ صفحه اصلی - قسمت پایینی'},
        ),
    ]
