# Generated by Django 4.2 on 2023-07-28 18:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_footercapability_alter_advertisebottomindex_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footercapability',
            name='image',
            field=models.ImageField(upload_to='footer/capability/%y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'svg', 'jpeg', 'png'])]),
        ),
    ]
