# Generated by Django 4.2 on 2023-07-28 19:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_alter_footercapability_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footercapability',
            name='image',
            field=models.FileField(upload_to='footer/capability/%y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'svg', 'jpeg', 'png'])]),
        ),
    ]
