# Generated by Django 4.2 on 2023-07-11 18:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='phone',
            field=models.CharField(max_length=15, validators=[django.core.validators.MaxLengthValidator(11), django.core.validators.MinLengthValidator(11)], verbose_name='تلفن'),
        ),
    ]
