# Generated by Django 4.2 on 2023-07-09 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربران'},
        ),
        migrations.AddField(
            model_name='user',
            name='activated_code',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='کد فعالسازی'),
        ),
    ]
